services:
  chat:
    image: navrin/css2chat
    build: .
#    user: css2_llm
    ports:
      - "8501:8501"
    expose:
      - 8501
    volumes:
      - ./.env:/src/.env
    depends_on:
      - db
    links:
      - "db:postgres"
    environment:
      PROJECT_ROOT: "/src"
      DB_HOST_SET: "postgres"
    env_file:
       - .env

  db:
    image: "postgres:16.2-bookworm"
    build:
      dockerfile: Dockerfile-postgres
      context: .
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    volumes:
      - ./database_schema:/docker-entrypoint-initdb.d/
      - ./example_data:/data
    #ports:
    #  - "5432:5432"
