services:
  chat:
    image: navrin/css2chat
#    user: css2_llm
    ports:
      - "8501:8501"
    expose:
      - 8501
    volumes:
      - ./.env:/src/.env
    depends_on:
      - db
    links:
      - "db:postgres"
    environment:
      PROJECT_ROOT: "/src"
      DB_HOST_SET: "postgres"
    env_file:
       - .env

  db:
    image: navrin/css2db
    shm_size: 128mb
    restart: always
    env_file:
      - .env
