CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS modifier CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS store CASCADE;
DROP TABLE IF EXISTS sale_item CASCADE;
DROP TABLE IF EXISTS sale_item_modifier CASCADE;
DROP TABLE IF EXISTS product_modifier CASCADE;
DROP TABLE IF EXISTS product_review CASCADE;