CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE product CASCADE;
DROP TABLE modifier CASCADE;
DROP TABLE customer CASCADE;
DROP TABLE sale CASCADE;
DROP TABLE store CASCADE;
DROP TABLE sale_item CASCADE;
DROP TABLE sale_item_modifier CASCADE;
DROP TABLE product_modifier CASCADE;
