CREATE TABLE product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    name varchar(50) NOT NULL,
    description varchar,
    price float NOT NULL
);
CREATE TABLE product_modifier (
    product_id INTEGER REFERENCES product(id),
    modifier_id INTEGER REFERENCES modifier(id),
    CONSTRAINT product_modifier_pk PRIMARY KEY (product_id, modifier_id)
);

