CREATE TABLE sale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customer(id),
    store INTEGER REFERENCES store(id)
);

CREATE TABLE sale_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER REFERENCES sale(id),
    product_id INTEGER REFERENCES product(id),
    quantity INTEGER
--     CONSTRAINT sale_item_pk PRIMARY KEY (sale_id, product_id)
);

CREATE TABLE sale_item_modifier (
    sale_item_id INTEGER REFERENCES sale_item(id),
    modifier_id INTEGER REFERENCES modifier(id),
    CONSTRAINT sale_item_modifier_pk PRIMARY KEY (sale_item_id, modifier_id)
);